#!/bin/bash
set -e

echo "> Binding to port $PORT"
echo "proxy_listen=0.0.0.0:$PORT reuseport backlog=16384" >> /etc/kong/kong.conf

echo "> Parsing the database settings"
# Parse the database URL
url="$DATABASE_URL"
dbtype=${url%%://*}
url_without_scheme=${url#*://}  # strip URL scheme
rest=${url_without_scheme#*/}
user_password_host_port=${url_without_scheme%%/*}
host_port=${user_password_host_port#*@}
user_password=${user_password_host_port%$host_port}
user_password=${user_password%@}
host=${host_port%:*}
port=${host_port#$host}
port=${port#:}
user=${user_password%:*}
password=${user_password#$user}
password=${password#:}
dbname=${rest%\?*}
querystring=${rest#$dbname}

# Set Kong database settings
echo "
pg_host=$host
pg_port=$port
pg_user=$user
pg_password=$password
pg_database=$dbname" >> /etc/kong/kong.conf


echo "> Starting Kong..."
./docker-entrypoint.sh