#!/bin/bash
set -e

KONG_LOG_LEVEL=warn

./docker-entrypoint.sh kong docker-start &

sleep 1

curl -sS -X POST http://127.0.0.1:8001/services \
  --data name=admin-api \
  --data host=127.0.0.1 \
  --data port=8001

curl -sS -X POST http://127.0.0.1:8001/services/admin-api/routes \
  --data paths[]=/$ADMIN_PATH

./docker-entrypoint.sh kong stop