#!/bin/bash
set -e

./docker-entrypoint.sh kong docker-start &

# Give Kong a moment to boot
sleep 2

curl -sS -X PUT http://127.0.0.1:8001/services/admin-api \
  --data host=127.0.0.1 \
  --data port=8001

curl -sS -X PUT http://127.0.0.1:8001/routes/admin \
  --data service.name=admin-api

./docker-entrypoint.sh kong stop